Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0230bd60aa48260c6
      InstanceType: t2.micro
      KeyName: da-comp
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            yum update -y
            yum install -y httpd 
            cd /var/www/html
            wget https://github.com/Asonti04/formation/archive/refs/heads/main.zip
            unzip main.zip
            cp -r formation-main/* /var/www/html/index.html
            rm -rf formation-main main.zip
            systemctl enable httpd
            systemctl start httpd
